dim <- ncol(chi2_row)
image(1:dim, 1:dim, chi2_row, axes = F, xlab = "", ylab= "")
axis(1, 1:dim, row.names(chi2_row), cex.axis= 1, las = 3)
axis(2, 1:dim, row.names(chi2_row), cex.axis= 1, las = 1)
text(expand.grid(1:dim, 1:dim), sprintf("%0.1f", chi2_row), cex = 1)